### ISSUE TITLE
Not working after PyCharm 2021.3.1 update

### ISSUE THREAD

**Issue by grodrigues142** [chornsby/django-migrations-pycharm-plugin#2]
Hi!  This plugin stop to work after PyCharm 2021.3.1 update
![Captura de Tela 2022-01-24 às 11 32 00](https://user-images.githubusercontent.com/5368048/150802164-eb0ce442-cfc4-45e5-a543-795f91335c2f.png)

**Comment by kiko33** [comment]
IDE internal error: Pycharm 2024.3 professional edition


com.intellij.diagnostic.PluginException: The default implementation of method `getId` is deprecated, `com.chornsby.intellij.plugins.django.MigrationRunConfigurationType$MigrationRunConfigurationFactory` must override it. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: com.chornsby.intellij.plugins.django.Migrations]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:134)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:78)
	at com.intellij.execution.impl.RunManagerImplKt.getFactoryKey(RunManagerImpl.kt:1475)
at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.getName(RunnerAndConfigurationSettingsImpl.kt:174)
at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.writeExternal(RunnerAndConfigurationSettingsImpl.kt:290)
	at com.intellij.execution.impl.TemplateDifferenceHelper.isTemplateModified(RunConfigurationSchemeManager.kt:150)
